### PR TITLE
web: update dependencies (2024-03-19)

### PR DESCRIPTION
**Pull request by dgdavid**
Update web dependencies to their latest versions via `npm update` and `npm install package-name@latest` when needed.

---

Previous update: https://github.com/openSUSE/agama/pull/985

### CODE REVIEW

**Review by imobachgs — COMMENTED** [review]
I am not sure whether it is worth it. It introduces some conflicts with the architecture_2024 branch and, after all, we should be merging them in one month.

I would only patch important security issues.

**Comment by dgdavid** [comment]
> I am not sure whether it is worth it. It introduces some conflicts with the architecture_2024 branch and, after all, we should be merging them in one month.
> 
> I would only patch important security issues.

I do not see conflicts in just to files a big problem. I can take care of them.

That said, I can live postponing the update until the mentioned branch is merged. But please, keep the PR open to not forget about it.

**Comment by imobachgs** [comment]
> I do not see conflicts in just two files a big problem. I can take care of them.
> 
> That said, I can live postponing the update until the mentioned branch is merged. But please, keep the PR open to not forget about it.

I like to avoid lockfiles merges if possible :-) I am not against this PR, but I do not see the benefit. I would rather prefer to update the dependencies in the `architecture_2024` branch instead.

**Review by imobachgs — APPROVED** [review]

**Comment by dgdavid** [comment]
> 
> I like to avoid lockfiles merges if possible :-) I am not against this PR, but I do not see the benefit. I would rather prefer to update the dependencies in the `architecture_2024` branch instead.

Ok, let's wait

**Comment by dgdavid** [comment]
Postponing the update until `architecture_2024` branch is ready. With a bit of luck we are not going to forget it.

**Pull request closed without merging**
