### PR TITLE
Update sv.po

### PR DESCRIPTION
**Pull request by bittin**
Update Swedish translation 6th November 2023

### CODE REVIEW

**Comment by lslezak** [comment]
Please, do not change the translations directly here, they are automatically overwritten by files from the https://github.com/openSUSE/agama-weblate repository.

I have updated it in https://github.com/openSUSE/agama-weblate/commit/0b2862fd471f3bcbc81a881d53d90a74c2d095d8

**Comment by bittin** [comment]
@lslezak alright did not know that sorry, had problems to login to Weblate, but thanks for putting it in the correct location

**Comment by bittin** [comment]
Updated the Swedish translation again today

**Comment by imobachgs** [comment]
@bittin Thanks! It will get updated with the next Weblate's submission.

**Comment by bittin** [comment]
@imobachgs @lslezak @lkocman 

Great see Agama test version 5 is out now with partial Swedish helping to test now in Virtualbox 
also there been problems with logging in to Weblate for a couple of days, where is the best place to report that so it get fixed?

**Comment by bittin** [comment]
> @imobachgs @lslezak @lkocman
> 
> Great see Agama test version 5 is out now with partial Swedish helping to test now in Virtualbox also there been problems with logging in to Weblate for a couple of days, where is the best place to report that so it get fixed?

sent a PR manually for now today until it get fixed

**Comment by bittin** [comment]
and Agama is at 100% Swedish again as i now can login to Weblate again

**Pull request closed without merging**
