### PR TITLE
Ensure that the software context is ready

### PR DESCRIPTION
**Pull request by imobachgs**
## Problem

The overview page is shown when the product is not selected. It is almost imperceptible for the human eye, but not for QA :smiley:

## Solution

* Make sure the software context is ready before loading the routes.

## Testing

- Tested manually

### CODE REVIEW

**Review by joseivanlopez — APPROVED** [review]
LGTM

**Review by dgdavid — APPROVED** [review]
LGTM, thanks a lot for such a quick fix!

**Comment by imobachgs** [comment]
Checking the problem in the CI, the problem turned out to be more complex. The comparison was correct (`null`: no product, `undefined`: not initialized). So, I decided to ensure the software context is ready before loading the rest of the application.

**Comment by dgdavid** [comment]
> Checking the problem in the CI, the problem turned out to be more complex. The comparison was correct (`null`: no product, `undefined`: not initialized)

Ah, right. I forgot about that detail. We're using similar approach in other places. Good you realized about it. Thanks.

> So, I decided to ensure the software context is ready before loading the rest of the application.

Better, 👍

**Pull request closed without merging**
